[package]
name = "porteurbars"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]

[[bin]]
doc = false
name = "foo"
path = "src/bin/porteurbars.rs"

[dependencies]
log = "*"
env_logger = "0.3"
difference = "0.4"
tempdir = "0.3"
handlebars = "0.16"
clap = "2.5"
regex = "0.1"
hyper = "0.9"
tar = "*"
flate2 = "*"
walkdir = "0.1"
