[package]
name = "porteurbars"
version = "0.0.0"
authors = ["softprops <d.tangren@gmail.com>"]

[[bin]]
doc = false
name = "porteurbars"
path = "src/bin/porteurbars.rs"

[dependencies]
lazy_static = "0.1"
log = "0.3"
env_logger = "0.3"
difference = "0.4"
tempdir = "0.3"
handlebars = "0.24"
clap = "2.20"
regex = "0.2"
walkdir = "1.0"
git2 = "0.6.3"
